### ISSUE TITLE
Block Device  Can't list images : error http 500

### ISSUE THREAD

**Issue by djcao** [inkscope/inkscope#101]
hello
        click Block Device images,status is "  Can't list images : error http 500"

error info is 
GET http://192.168.15.6:8080/inkscopeCtrl/RBD/images 500 (INTERNAL SERVER ERROR)

log info
/var/log/inkscope/webserver_access.log
192.168.4.8 - - [29/Jun/2017:19:16:40 +0800] "GET /inkscopeCtrl/RBD/images HTTP/1.1" 500 291

**Comment by djcao** [comment]
I fix it
if the inkscope is not a node of ceph cluster
you must copy the ceph.admin.keyring to the inkscope node and run next cmd
"chmod +r /etc/ceph/ceph.client.admin.keyring "

**Comment by A-Dechorgnat** [comment]
Thay's it!
To show Block device images, the Inkscope server has to run rbd commands. To do so, ceph must be installed and configured on the Inkscope server

**Comment by djcao** [comment]
I,m sorry. i got en other problem。
when i test the ceph plugin by collectd . I run then python code " python ceph_pg_plugin.py"
the error info is :
 File "ceph_pg_plugin.py", line 98, in <module>
    collectd.register_config(configure_callback)
AttributeError: 'module' object has no attribute 'register_config'

Is there anything wrong with collectd version  or python module?

**Comment by djcao** [comment]
pip install python-collectd-mock (0.0.2)
