### ISSUE TITLE
Sysprobe active(exited)

### ISSUE THREAD

**Issue by utkudarilmaz** [inkscope/inkscope#111]
I install the inkScope, sysprobe, cephprobe on a ceph node. This ceph node monitoring very well. But i install the sysprobe on another ceph node that is connect same network but in this node "service sysprobe status" output like this:
_● sysprobe.service - LSB: Example initscript
   Loaded: loaded (/etc/init.d/sysprobe; generated; vendor preset: enabled)
   Active: active (exited) since Wed 2018-06-27 18:25:03 +03; 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1389 ExecStop=/etc/init.d/sysprobe stop (code=exited, status=0/SUCCESS)
  Process: 1393 ExecStart=/etc/init.d/sysprobe start (code=exited, status=0/SUCCESS)

Jun 27 18:25:03 ceph2 systemd[1]: Stopped LSB: Example initscript.
Jun 27 18:25:03 ceph2 systemd[1]: Starting LSB: Example initscript...
Jun 27 18:25:03 ceph2 sysprobe[1393]: Starting sysprob daemon
Jun 27 18:25:03 ceph2 systemd[1]: Started LSB: Example initscript._

I cant seem the ceph2 node on inkscope host. I followed the instruction where wiki page. What can be the problem?

**Comment by A-Dechorgnat** [comment]
Hi,
Please share your /var/log/inkscope/sysprobe.log

**Comment by utkudarilmaz** [comment]
My mongodb service only listen to localhost, so i changed bindip to 0.0.0.0 in /etc/mongod.conf, problem has solved.
