### ISSUE TITLE
Configuration Settings

### ISSUE THREAD

**Issue by utkudarilmaz** [inkscope/inkscope#112]
Hi,
I wanna oparete inkscope on a non ceph node. My inkscope host machine's ip adress is 192.168.2.62. 
My ceph node have two ip adress. One of them is 192.168.122.51, other ip adress is 172.16.5.201. 
Also ceph-rest-api is run on ceph node.
Now i have a few questions. 

1- On inkscope host my /opt/inkscope/etc/inkscope.conf configuration file, what should i write ceph-rest-api section? 
2- On which machine should i run cephprobe?

**Comment by ghisl1** [comment]
Hi,
I suggest you to reinstall inkscope using the new inkscope-ansible procedure.
the installation will rely aon wsgi access to the ceph-rest-api (more efficient)
It is mandatory to run inkscope on a server where ceph is installed and configured (ceph.conf and admin key) because inkscope uses ceph directly for some features.

Bets regards

**Comment by utkudarilmaz** [comment]
So do you mean i can't install the inkscope to non ceph node host? 
Also, i install the inkscope on non ceph node, i configured the /etc/apache2/sites-available/inkScope.conf stand alone ceph-rest-api settings. Also i can't run cephprobe service on inkscope host.
```
2018-07-06 11:29:31.987769 -- CephProbe loading
clusterName =  ceph
ceph_conf =  /etc/ceph/ceph.conf
ceph_rest_api =  172.16.5.201:5000
ceph_rest_api_subfolder =  
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 874, in <module>
    daemon.start()
  File "/opt/inkscope/bin/daemon.py", line 87, in start
    self.run()
  File "/opt/inkscope/bin/cephprobe.py", line 710, in run
    fsid = ceph_conf_global(ceph_conf_file, 'fsid')
  File "/opt/inkscope/bin/cephprobe.py", line 117, in ceph_conf_global
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
**Note : I did copied the ceph.conf and keyring from the ceph where ceph-rest-api is running.**

So i see the information about ceph cluster on first page but i can not seem anything on osd's page.
[![Screenshot_from_2018-07-06_12-12-24.png](https://s8.postimg.cc/5j3elaph1/Screenshot_from_2018-07-06_12-12-24.png)](https://postimg.cc/image/6ldl3u8a9/)
[![Screenshot_from_2018-07-06_12-12-32.png](https://s8.postimg.cc/ft5tkjn2d/Screenshot_from_2018-07-06_12-12-32.png)](https://postimg.cc/image/mwdp05sht/)

**Comment by A-Dechorgnat** [comment]
If you can't see osd info, it is due to the cephprobe error in your log.

It seems that it can't access ceph conf to retrieve the fsid.

**Comment by utkudarilmaz** [comment]
But i copied the ceph mon node's conf file and keyring file to inkscope host. 
Does inkscope and ceph clusters have to be same ip block?
Also, where i should run cephprobe? On inkscope host or ceph host?

**Comment by A-Dechorgnat** [comment]
cephprobe can be installed either on ceph node or inkscope node.
In each case, it must have access to ceph_rest_api, mongodb database and and ceph-config command

**Comment by utkudarilmaz** [comment]
I suppose, trouble about my network settings. Thanks.

**Comment by utkudarilmaz** [comment]
Hi again, my inscope hiearchy is : 

[![inkscope.jpg](https://s8.postimg.cc/bdzum5pf9/inkscope.jpg)](https://postimg.cc/image/qmprzxj3l/)

I wanna run inkscope on seperate server from cephs. I did connect the ceph-rest-api via http_proxy settings successfuly. And my inkscope homepage is look like this:
[![Screenshot_from_2018-07-13_17-43-48.png](https://s8.postimg.cc/jkruddkj9/Screenshot_from_2018-07-13_17-43-48.png)](https://postimg.cc/image/jxj8jk2sx/)

Osd's seems on osdPerf page:
[![Screenshot_from_2018-07-13_17-43-55.png](https://s8.postimg.cc/6gma0p079/Screenshot_from_2018-07-13_17-43-55.png)](https://postimg.cc/image/6tdo6vigx/)

But i can't see other settings on other pages.

[![Screenshot_from_2018-07-13_17-43-59.png](https://s8.postimg.cc/ti2v6g7kl/Screenshot_from_2018-07-13_17-43-59.png)](https://postimg.cc/image/ythrr5tn5/)

 I run cephprobe on ceph1 machine. Cephprobe running but give me a some error. The log file is : 

```
2018-07-13 17:56:46.823831 -- WARNING : process_status did not work :  'health'
2018-07-13 17:56:48.115434 -- Process OSDDump
2018-07-13 17:56:49.824209 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 226, in process_status
    health_services_list = c_status['output']['health']['health']['health_services']
KeyError: 'health'
2018-07-13 17:56:49.828913 -- WARNING : process_status did not work :  'health'
2018-07-13 17:56:51.131822 -- Process OSDDump
2018-07-13 17:56:52.829406 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 226, in process_status
    health_services_list = c_status['output']['health']['health']['health_services']
KeyError: 'health'
2018-07-13 17:56:52.836751 -- WARNING : process_status did not work :  'health'
2018-07-13 17:56:54.150189 -- Process OSDDump
2018-07-13 17:56:55.837166 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 226, in process_status
    health_services_list = c_status['output']['health']['health']['health_services']
KeyError: 'health'
2018-07-13 17:56:55.849493 -- WARNING : process_status did not work :  'health'
2018-07-13 17:56:57.198548 -- Process OSDDump
2018-07-13 17:56:58.849967 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 226, in process_status
    health_services_list = c_status['output']['health']['health']['health_services']
KeyError: 'health'
2018-07-13 17:56:58.854614 -- WARNING : process_status did not work :  'health'
2018-07-13 17:57:00.216089 -- Process OSDDump
2018-07-13 17:57:01.855004 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 226, in process_status
    health_services_list = c_status['output']['health']['health']['health_services']
KeyError: 'health'
2018-07-13 17:57:01.859381 -- WARNING : process_status did not work :  'health'
2018-07-13 17:57:03.232563 -- Process OSDDump
2018-07-13 17:57:04.859819 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 226, in process_status
    health_services_list = c_status['output']['health']['health']['health_services']
KeyError: 'health'
2018-07-13 17:57:04.864194 -- WARNING : process_status did not work :  'health'
2018-07-13 17:57:06.249557 -- Process OSDDump
```

My inkscope.conf file look like this:
```
{    
    "ceph_conf": "/etc/ceph/ceph.conf",
    "ceph_rest_api": "192.168.2.92:5000",
    "mongodb_host" : "192.168.2.62",
    "mongodb_set" : "",
    "mongodb_replicaSet" : "",
    "mongodb_read_preference" : "ReadPreference.SECONDARY_PREFERRED",
    "mongodb_port" : 27017,
    "mongodb_user":"",
    "mongodb_passwd":"",
    "is_mongo_authenticate" : 0,
    "is_mongo_replicat" : 0,
    "influxdb_endpoint":"",
    "cluster": "ceph",
    "platform": "Ekinoks Ceph Management",
    "status_refresh": 3,
    "osd_dump_refresh": 3,
    "pg_dump_refresh": 60,
    "crushmap_refresh": 60,
    "df_refresh": 60,
    "cluster_window": 1200,
    "osd_window": 1200,
    "pool_window": 1200,
    "mem_refresh": 60,
    "swap_refresh": 600,
    "disk_refresh": 60,
    "partition_refresh": 60,
    "cpu_refresh": 30,
    "net_refresh": 30,
    "mem_window": 1200,
    "swap_window": 3600,
    "disk_window": 1200,
    "partition_window": 1200,
    "cpu_window": 1200,
    "net_window": 1200,
    "inkscope_root" : "192.168.2.62:8080",
    "radosgw_url": "http://192.168.2.92:7480",
    "radosgw_admin": "admin",
    "radosgw_key": "access-key",
    "radosgw_secret": "secret-key"
}
```

Is inkscope can't run on non-ceph machine? Because, if i install the inkscope on machine which is running ceph-rest-api, everything runs fine.

I can't find the problem. Please help :(

**Comment by A-Dechorgnat** [comment]
First thing, I see at the menu level "logged as " _nothing_. This is not normal
Please look at /var/log/inkscope/webserver_error.log
You will certainly find an error about connection to mongo ...

**Comment by A-Dechorgnat** [comment]
Page OSDs performance take info from rest_api but OSD status get info from mongo
it seems that Cephprobe can't access mongo .

**Comment by A-Dechorgnat** [comment]
I think also that you don't run the last version of cephprobe. Line numbers are not in phase with master branch

**Comment by utkudarilmaz** [comment]
I upgrade cephprobe and that error is fixed:
```
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 226, in process_status
    health_services_list = c_status['output']['health']['health']['health_services']
KeyError: 'health'
2018-07-13 17:57:01.859381 -- WARNING : process_status did not work :  'health'
2018-07-13 17:57:03.232563 -- Process OSDDump
2018-07-13 17:57:04.859819 -- Process Status
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 226, in process_status
    health_services_list = c_status['output']['health']['health']['health_services']
KeyError: 'health'
2018-07-13 17:57:04.864194 -- WARNING : process_status did not work :  'health'
2018-07-13 17:57:06.249557 -- Process OSDDump
```
Now cephprobe's and sysprobe's has no more error on log file. 
I checked the mongodb about information is coming, everything look good also there.
On /var/log/inkscope/webserver_error.log output below.
```
[Mon Jul 16 17:34:52.884962 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868] mod_wsgi (pid=15617): Target WSGI script '/var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi' cannot be loaded as Python module., referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.884999 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868] mod_wsgi (pid=15617): Exception occurred processing WSGI script '/var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi'., referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885021 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868] Traceback (most recent call last):, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885042 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868]   File "/var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi", line 13, in <module>, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885073 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868]     from inkscopeCtrlcore import app as application, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885082 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868]   File "/var/www/inkscope/inkscopeCtrl/inkscopeCtrlcore.py", line 32, in <module>, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885094 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868]     from poolsCtrl import PoolsCtrl,Pools, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885101 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868]   File "/var/www/inkscope/inkscopeCtrl/poolsCtrl.py", line 6, in <module>, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885111 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868]     import requests, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885132 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868] ImportError: No module named requests, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
```

Also on http://192.168.2.97:8080/inkscopeViz/osds.html have that error:
`Error: [ngRepeat:dupes] http://errors.angularjs.org/1.2.21/ngRepeat/dupes?p0=osd%20in%20data%7CorderBy%3A'id'&p1=string%3AT y/<@http://192.168.2.97:8080/inkscopeViz/scripts/angular/angular.min.js:6:450 link/<@http://192.168.2.97:8080/inkscopeViz/scripts/angular/angular.min.js:199:86 $watchCollection/<@http://192.168.2.97:8080/inkscopeViz/scripts/angular/angular.min.js:108:145 $digest@http://192.168.2.97:8080/inkscopeViz/scripts/angular/angular.min.js:109:211 $apply@http://192.168.2.97:8080/inkscopeViz/scripts/angular/angular.min.js:112:171 h@http://192.168.2.97:8080/inkscopeViz/scripts/angular/angular.min.js:72:298 w@http://192.168.2.97:8080/inkscopeViz/scripts/angular/angular.min.js:77:288 we/</A.onreadystatechange@http://192.168.2.97:8080/inkscopeViz/scripts/angular/angular.min.js:78:375`

I clone the master branch and change the /var/www/inkscope files but it didn't solve problem.

Could the problem be that i running inkscope and ceph at discrete machine? Because if i run the inkscope with wsgi application on same machine where ceph installed, its working without problem.
Are you tested inkscope on standalone server with discrete inkscope host and ceph host before?

**Comment by utkudarilmaz** [comment]
Additionally mostly page has 500 error. Errors coming from http://192.168.2.97:8080/inkscopeCtrl/xxx or http://192.168.2.97:8080/inkscopeCtrl/<my_database_name>.
 [![Screenshot_from_2018-07-16_18-07-04.png](https://s8.postimg.cc/v9u1ptwpx/Screenshot_from_2018-07-16_18-07-04.png)](https://postimg.cc/image/6gkhp6dpd/)

**Comment by A-Dechorgnat** [comment]
At this stage you **must** look at /var/log/inkscope/webserver_error.log

You will certainly find an error about connection to mongo .. (error 500 for GET conf.json and GET osd?depth=2)

>  Could the problem be that i running inkscope and ceph at discrete machine? Because if i run the inkscope with wsgi application on same machine where ceph installed, its working without problem.
    Are you tested inkscope on standalone server with discrete inkscope host and ceph host before?

Yes we have several platform and generally inkscope is not on a ceph server. By this, I mean that the inkscope server doesn't carry any osd or mon... 
However, ceph is installed on the inkscope server, and has a ceph.conf and keyrings

**Comment by A-Dechorgnat** [comment]
Sorry, I didn't read your entire message and missed your /var/log/inkscope/webserver_error.log:

> `[MonJul 16 17:34:52.885094 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868]     from poolsCtrl import PoolsCtrl,Pools, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885101 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868]   File "/var/www/inkscope/inkscopeCtrl/poolsCtrl.py", line 6, in <module>, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885111 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868]     import requests, referer: http://192.168.2.97:8080/inkscopeViz/osds.html
[Mon Jul 16 17:34:52.885132 2018] [wsgi:error] [pid 15617:tid 140719918831360] [client 192.168.2.149:60868] ImportError: No module named requests, referer: http://192.168.2.97:8080/inkscopeViz/osds.html` 

**No module named requests** :  There are missing python modules.

Perhaps you can try
`pip install -r requirements.txt `

and after share the result of
`pip list`

**Comment by utkudarilmaz** [comment]
I installed all requirements at the requirements.txt but problem still doesn't fix.

My pip list output:
```
beautifulsoup4 (4.5.3)
blinker (1.4)
boto (2.48.0)
ceph-deploy (2.0.1)
ceph-detect-init (1.0.1)
ceph-disk (1.0.0)
ceph-volume (1.0.0)
cephfs (2.0.0)
chardet (2.3.0)
CherryPy (3.5.0)
click (6.6)
colorama (0.3.7)
cryptography (1.7.1)
dnspython (1.15.0)
enum34 (1.1.6)
Flask (0.10.1)
Flask-Login (0.3.0)
Flask-Mail (0.7.3)
Flask-Principal (0.3.3)
Flask-WTF (0.8)
FormEncode (1.3.0)
gitdb2 (2.0.0)
GitPython (2.1.1)
idna (2.2)
ipaddress (1.0.17)
itsdangerous (0.24)
Jinja2 (2.10)
keyring (10.1)
keyrings.alt (1.3)
logutils (0.3.3)
Mako (1.0.6)
MarkupSafe (0.23)
passlib (1.6.4)
Paste (2.0.3)
PasteDeploy (1.5.2)
pecan (1.1.2)
pip (9.0.1)
prettytable (0.7.2)
psutil (2.1.3)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pygobject (3.22.0)
pymongo (2.7)
pyOpenSSL (16.2.0)
pyxdg (0.25)
rados (2.0.0)
rbd (2.0.0)
repoze.lru (0.6)
requests (2.12.4)
rgw (2.0.0)
Routes (2.3.1)
SecretStorage (2.3.1)
setuptools (33.1.1)
simple-json (1.1)
simplegeneric (0.8.1)
simplejson (3.15.0)
singledispatch (3.4.0.3)
six (1.10.0)
smmap2 (2.0.1)
Tempita (0.5.2)
urllib3 (1.19.1)
waitress (1.0.1)
WebOb (1.6.2)
WebTest (2.0.24)
Werkzeug (0.14.1)
wheel (0.29.0)
WTForms (2.2.1)
```

**Comment by utkudarilmaz** [comment]
I install the inkscope-admviz_1.4.0.2.deb package you shared on http://inkscope.blogspot.com/2015/12/inkscope-v13-installation-on-debian.html. 
After i install the package, osd status like pages viewed very well but home page is broked. After that i clone the inkscope from master to /var/www/ directory and now inkscope is running very well. 

What is in the this package? And what is this package install?

**Comment by A-Dechorgnat** [comment]
The packages are out of date and not maintained. We propose now to install Inkscope with an ansible playbook (https://github.com/inkscope/inkscope-ansible)
