### ISSUE TITLE
pools-pgs-osds page's graphics not viewing 

### ISSUE THREAD

**Issue by utkudarilmaz** [inkscope/inkscope#113]
Hello, 
 
I installed the inkscope with ansible installation. When i enter the http://172.16.5.50/inkscopeViz/poolspgsosds.html page and click show button but graphics not loading very well. 
When i opening the browser console, there is no error. 
My browser is Firefox and also i trying with Chromium browser but result is same.

Graphics look like:

[![Inkscope-_Pools-_Graphs.png](https://s8.postimg.cc/daldd6lj9/Inkscope-_Pools-_Graphs.png)](https://postimg.cc/image/qeqxpvdkx/)

**Comment by ghisl1** [comment]
Hi,
Did you select "only unhealthy pgs" ?
(i can't see in the screensht)

brgds

**Comment by utkudarilmaz** [comment]
Yes, i choose now but result is same.

**Comment by ghisl1** [comment]
.rgw.root looks unhealthy.
can you list the pools using ceph pool management?

**Comment by ghisl1** [comment]
Hi, 
the issue is not related to inkscope but surely at ceph side
 you'll find information in inkscope dashboard and using the ceph cli

Brgds

**Comment by utkudarilmaz** [comment]
Thanks so much for helping.
If i solve the problem i will inform.

Best regards.
