### ISSUE TITLE
OsdMap doesn't display status for buckets other than OSDs

### ISSUE THREAD

**Issue by antgilles** [inkscope/inkscope#34]
Hello,
First of all, thanks a lot for your work. 
I am trying your application and it is helpfull to understand ceph behaviour that I don't know well. 

I encounter a problem in the display of the OSDMAP : 
buckets other than osd are not colorized when I first display the OsdMap 
![capture d ecran de 2014-12-24 19 06 57](https://cloud.githubusercontent.com/assets/10283140/5550236/19f3799e-8ba0-11e4-8fcd-ebfaf932c2e3.png)

When I resize the browser page the host buckets are colorized.  
![capture d ecran de 2014-12-24 19 09 36](https://cloud.githubusercontent.com/assets/10283140/5550242/700f9d6c-8ba0-11e4-8e58-77535abddd5d.png)

And don't have any value for the root=default but maybe it's normal. 

Merry Xmas
Antoine

**Comment by A-Dechorgnat** [comment]
I have also this issue in some cases but I have not yet found why. I'll have a look at this soon.

**Comment by A-Dechorgnat** [comment]
Issue reproducted on dev environment.
In some case, partition.stat is null for one or several OSDs

**Comment by A-Dechorgnat** [comment]
the issue has not been reproduced
