### ISSUE TITLE
Ceph 0.87.1: liblttng-ust breaks inkscopeCtrl/S3ObjectCtrl.py error exceptions

### ISSUE THREAD

**Issue by xvillaneau** [inkscope/inkscope#36]
**Bug context :** Ubuntu 14.04.2, Python 2.7.6, Ceph 0.87.1, Apache 2.4.7, WSGI 3.4-4ubuntu2, latest Inkscope master

The latest version of Ceph Giant (0.87.1, released yesterday) now uses liblttng-ust (for tracing), but this causes issues when the ceph command is called in the WGSI environment:

>[Fri Feb 27 14:52:45.315719 2015] [:error] [pid 5904:tid 139928306390784] INFO     ___getPoolId(poolname=.rgw.buckets)
>[Fri Feb 27 14:52:45.316027 2015] [:error] [pid 5904:tid 139928306390784] ___Building unix with = ceph osd pool stats  ___args=[".rgw.buckets"] ___filters=[]
>[Fri Feb 27 14:52:45.521828 2015] [:error] [pid 5904:tid 139928306390784] ERROR    Exception on /S3/object [GET]
>[Fri Feb 27 14:52:45.521866 2015] [:error] [pid 5904:tid 139928306390784] Traceback (most recent call last):
>[Fri Feb 27 14:52:45.521874 2015] [:error] [pid 5904:tid 139928306390784]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
>[Fri Feb 27 14:52:45.521880 2015] [:error] [pid 5904:tid 139928306390784]     response = self.full_dispatch_request()
>[Fri Feb 27 14:52:45.521885 2015] [:error] [pid 5904:tid 139928306390784]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
>[Fri Feb 27 14:52:45.521891 2015] [:error] [pid 5904:tid 139928306390784]     rv = self.handle_user_exception(e)
>[Fri Feb 27 14:52:45.521897 2015] [:error] [pid 5904:tid 139928306390784]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
>[Fri Feb 27 14:52:45.521907 2015] [:error] [pid 5904:tid 139928306390784]     reraise(exc_type, exc_value, tb)
>[Fri Feb 27 14:52:45.521912 2015] [:error] [pid 5904:tid 139928306390784]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
>[Fri Feb 27 14:52:45.521917 2015] [:error] [pid 5904:tid 139928306390784]     rv = self.dispatch_request()
>[Fri Feb 27 14:52:45.521922 2015] [:error] [pid 5904:tid 139928306390784]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
>[Fri Feb 27 14:52:45.521927 2015] [:error] [pid 5904:tid 139928306390784]     return self.view_functions[rule.endpoint](**req.view_args)
>[Fri Feb 27 14:52:45.521932 2015] [:error] [pid 5904:tid 139928306390784]   File "/var/www/inkScope/inkscopeCtrl/inkscopeCtrlcore.py", line 110, in getObjectStructure
>[Fri Feb 27 14:52:45.521937 2015] [:error] [pid 5904:tid 139928306390784]     return Response(S3ObjectCtrl(conf).getObjectStructure(),mimetype='application/json')
>[Fri Feb 27 14:52:45.521943 2015] [:error] [pid 5904:tid 139928306390784]   File "/var/www/inkScope/inkscopeCtrl/S3ObjectCtrl.py", line 74, in getObjectStructure
>[Fri Feb 27 14:52:45.521949 2015] [:error] [pid 5904:tid 139928306390784]     poolid = self.getPoolId(poolname)
>[Fri Feb 27 14:52:45.521958 2015] [:error] [pid 5904:tid 139928306390784]   File "/var/www/inkScope/inkscopeCtrl/S3ObjectCtrl.py", line 153, in getPoolId
>[Fri Feb 27 14:52:45.521964 2015] [:error] [pid 5904:tid 139928306390784]     outdata = self.executeCmd('ceph osd pool stats ', [poolname], [])
>[Fri Feb 27 14:52:45.521969 2015] [:error] [pid 5904:tid 139928306390784]   File "/var/www/inkScope/inkscopeCtrl/S3ObjectCtrl.py", line 354, in executeCmd
>[Fri Feb 27 14:52:45.521975 2015] [:error] [pid 5904:tid 139928306390784]     raise RuntimeError('unable to execute the command[%s] , Reason= %s' % (cmd, errdata))
>[Fri Feb 27 14:52:45.521980 2015] [:error] [pid 5904:tid 139928306390784] RuntimeError: unable to execute the command[ceph osd pool stats .rgw.buckets] , Reason= libust[6107/6107]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305)

The absence of HOME in the Apache environment doesn't please LTTng which raises a warning, but as implemented in `S3ObjectCtrl.py` any stderr output raises an exception and stops the script. This occurs in methods `executeCmd` (l. 352) and `getChunks` (l. 464).

An easy fix (which I've tried) is to avoid raising the exception if `errdata` matches the known error string, but that's *very* ugly. Maybe there are better ways to avoid this issue (ignore warnings, change ceph call).

**Comment by A-Dechorgnat** [comment]
Thanks for the feedback, I'll take a look at this.

**Comment by A-Dechorgnat** [comment]
not reproduced in 0.94 (0.87 was not a LTS)
