### ISSUE TITLE
Missing OSD stats

### ISSUE THREAD

**Issue by stuartbfox** [inkscope/inkscope#46]
Hi again :)

Im now pretty sure I have everything configured and running correctly, 5 node cluster, 60 osd's, 3 mons and several clients. All appears to be working fine apart from stats about osd's. Also, only osd0-4 show up in green. There is nothing in the logs, even at debug level. I've attached a screenshot for a better explaination.
![screen shot 2015-03-27 at 8 55 40 pm](https://cloud.githubusercontent.com/assets/1537582/6879747/53ba444c-d4c4-11e4-8d60-2e78fed72da6.png)

Let me know if there's anything else I can provide

**Comment by A-Dechorgnat** [comment]
Release 1.2 could be the clue

**Comment by A-Dechorgnat** [comment]
not reproduced

**Comment by chencaijin** [comment]
Hello, I found this error on inkscope : some osd stats are missing

any solution?
