### ISSUE TITLE
Viewing Inkscope in browser consumes large amounts of bandwidth

### ISSUE THREAD

**Issue by fiskn** [inkscope/inkscope#49]
We are viewing the InkScope page in a browser in a remote office, the actual InkScope install is located in the same datacenter as the Ceph Cluster.

I'm seeing an almost constant 4Mb/s worth of traffic coming from the InkScope server to my browser. I performed a packet capture and it looks like all the raw Ceph data is being sent to the browser.

Is this correct and intended behaviour?

**Comment by A-Dechorgnat** [comment]
We've change the dashboard to reduice the amount of data downloaded by the browser.
This is in commit f2274593d138a3276684b4f785def61dff1aa744 and will be in release V1.2

**Comment by fiskn** [comment]
Brilliant, thanks for the swift response
