### ISSUE TITLE
when I use uwsgi to analyze inkscopectrl,the script always return 404

### ISSUE THREAD

**Issue by guanglost** [inkscope/inkscope#57]
use uwsgi line:
          uwsgi -s 127.0.0.1:9090 --processes 2 --enable-threads --plugins python --pythonpath /var/www/inkscope/inkscopeCtrl --wsgi-file /var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi --callable application

and nginx config:
        location /inkscopeCtrl/ {
                include uwsgi_params;
                uwsgi_pass 127.0.0.1:9090;
        }
uwsgi log out:

added /var/www/inkscope/inkscopeCtrl/ to pythonpath.
DEBUG    Entering in S3ObjectCtrl class <<
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xeadf30 pid: 6195 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 6195, cores: 1)
spawned uWSGI worker 2 (pid: 6198, cores: 1)
[pid: 6195|app: 0|req: 1/1] 192.168.212.82 () {48 vars in 910 bytes} [Wed Oct 14 16:56:22 2015] POST /inkscopeCtrl/9a4a0881-ab91-4cff-97ea-29b99d54eb21/osd?depth=1 => generated 233 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)

Are there errors in my config? where?
Or the application is not fit for nginx? Only for  apache with mod_wsgi?

**Comment by A-Dechorgnat** [comment]
Inkscope has been developed and tested with Apache and WSGI.

As I don't know NGINX and UWSGI, I can't help you.

**Comment by guanglost** [comment]
Thank you for answering
