### ISSUE TITLE
ceph_rest_api_subfolder parameter parse error!

### ISSUE THREAD

**Issue by xiangdawei** [inkscope/inkscope#63]
If the field **"ceph_rest_api_subfolder"** in **/opt/inkscope/etc/inkscope.conf** blank,
it will get the error:
"GET **//**api/v0.1/osd/dump.json HTTP/1.1" 404(which should be "GET /api/v0.1/osd/dump.json HTTP/1.1")

and cannot display the detail information of pool

**Comment by Dechorgnat** [comment]
This is fixed by commit ae384ad

**Comment by xiangdawei** [comment]
I used the rpms package(version 1.3.1-2), it's best to recreate them! Thank you for your work!

**Comment by xiangdawei** [comment]
I used the rpm packages(version 1.3.1-2), it's fine to rebuild it! Thank
you for your work!
