### ISSUE TITLE
Osds are not mapped to hosts resulting in no osd space stats

### ISSUE THREAD

**Issue by sam-wouters** [inkscope/inkscope#64]
cephprobe looks up the osdhostid by "socket.getfqdn(hostaddr)".
However, when the osd hostaddr is not equal to the primary IP/hostname given by sysprobe, this breaks the mapping between osd and host tables.
As a result partition info can't be fetched and no used space info is shown.

**Comment by A-Dechorgnat** [comment]
Thank you for your help
