### ISSUE TITLE
objects degraded calculation error

### ISSUE THREAD

**Issue by mistur** [inkscope/inkscope#71]
Hello,

There is a mistake when the ration of degraded object is print :

![pg](https://cloud.githubusercontent.com/assets/15873680/15243482/26337b4c-18fc-11e6-97e5-0b9078ce87e8.png)

 1632251 objects degraded on 105764863 (0.015433%)  => should be 1.5433%

[patch.txt](https://github.com/inkscope/inkscope/files/262885/patch.txt)

**Comment by mistur** [comment]
we might add a .toFixed(6) to avoid too much digit after comma

[patch.txt](https://github.com/inkscope/inkscope/files/262914/patch.txt)

Yoann

**Comment by A-Dechorgnat** [comment]
Hi Yoann,
As you can see, the ration is calculated by ceph and just reused in inkscope display.
May be it is a ceph issue.

To verify this, please run this command:
ceph -s --format=json-pretty

in the pgmap section you will have something like:
  "pgmap": { "pgs_by_state": [...],
      "version": 2502367,
      "num_pgs": 1544,
      "data_bytes": 23558961471,
      "bytes_used": 66013945856,
      "bytes_avail": 25275944960,
      "bytes_total": 91289890816,
      "degraded_objects": 225,
      "degraded_total": 67819,
      "degraded_ratio": "0.332"},

You can now verify if the ratio is well computed?
Best regards,
Alain

**Comment by mistur** [comment]
here the ceph -s :

```
      pgmap v2779127: 4928 pgs, 18 pools, 55686 GB data, 18175 kobjects
            105 TB used, 276 TB / 381 TB avail
            1688355/105721218 objects degraded (1.597%)
            69698159/105721218 objects misplaced (65.926%)
```

and here ceph -s --format=json-pretty

```
    "pgmap": {
        "pgs_by_state": [
            {
                "state_name": "active+remapped+wait_backfill",
                "count": 2490
            },
            {
                "state_name": "active+clean",
                "count": 2357
            },
            {
                "state_name": "active+recovery_wait+degraded",
                "count": 63
            },
            {
                "state_name": "active+remapped+backfilling",
                "count": 16
            },
            {
                "state_name": "active+degraded+remapped+wait_backfill",
                "count": 1
            },
            {
                "state_name": "active+recovery_wait+degraded+remapped",
                "count": 1
            }
        ],
        "version": 2779072,
        "num_pgs": 4928,
        "data_bytes": 59785517477785,
        "bytes_used": 116033878183936,
        "bytes_avail": 303898714763264,
        "bytes_total": 419932592947200,
        "degraded_objects": 1686013,
        "degraded_total": 105713322,
        "degraded_ratio": 0.015949,
        "misplaced_objects": 69700546,
        "misplaced_total": 105713322,
        "misplaced_ratio": 0.659335,
        "recovering_objects_per_sec": 108,
        "recovering_bytes_per_sec": 373421229,
        "recovering_keys_per_sec": 0
    },
```

the ration in the json is not in % I guess 

Yoann

**Comment by A-Dechorgnat** [comment]
I see this is a problem of ceph version:
In my case (above), my test is with Firefly; the ratio is really in %
In your case, I see that ratio is a real ratio, not in %.

I will fix this by calculating the ratio by myself, independently from ceph version.
I will also add the misplaced objects indication

Thank you for having discovered this issue
