### ISSUE TITLE
inkscope 1.4.0.2 could not be installed by apt-get 

### ISSUE THREAD

**Issue by linuxhunter** [inkscope/inkscope#76]
1. write following to /etc/apt/sources.list.d/inkscope.list
deb https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS ./ 
2. update ubuntu repos.
#apt-get update
3.install inkscope-admviz.
#apt-get install inkscope-admviz
root@inkscope:~# apt-get install inkscope-admviz
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python-bson python-bson-ext python-gridfs python-pymongo python-pymongo-ext
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  apache2 apache2-bin apache2-data libapache2-mod-wsgi libapr1 libaprutil1
  libaprutil1-dbd-sqlite3 libaprutil1-ldap ssl-cert
Suggested packages:
  apache2-doc apache2-suexec-pristine apache2-suexec-custom apache2-utils
  openssl-blacklist
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data libapache2-mod-wsgi libapr1 libaprutil1
  libaprutil1-dbd-sqlite3 libaprutil1-ldap ssl-cert
The following packages will be upgraded:
  inkscope-admviz
1 upgraded, 9 newly installed, 0 to remove and 19 not upgraded.
Need to get 1,248 kB/2,599 kB of archives.
After this operation, 5,596 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  inkscope-admviz
Install these packages without verification? [y/N] y
Err https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS/ ./ inkscope-admviz 1.4.0-2
  Bad header line
E: Failed to fetch https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS/./inkscope-admviz_1.4.0.2.deb  Bad header line

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

what wrong with it?

**Comment by A-Dechorgnat** [comment]
Hello,
I think this is rather a network problem. I have just tried and it works. 
Could you retry please?

**Comment by linuxhunter** [comment]
Thanks for reply.
I retry it and get the same result. But when I use web browser to download it with https://raw.githubusercontent.com/inkscope/inkscope-packaging/master/DEBS/./inkscope-admviz_1.4.0.2.deb, it ok. 
what wrong with it? The OS is ubuntu14.04.4 amd64 server edition.

**Comment by linuxhunter** [comment]
Hi Dechorgnat,
    I retry it and all right. I guess it a network problem, I don't modify anything.

**Comment by A-Dechorgnat** [comment]
Good news
