### ISSUE TITLE
Default user for inkscope.

### ISSUE THREAD

**Issue by yangdongsheng** [inkscope/inkscope#77]
Hi guys, as a new comer to inkscope, I have setup an inkscope environment. But I found I don't know the default username and passwd for it. It could be a stupid question, but is there anyone can help me? thanx a lot.

**Comment by yangdongsheng** [comment]
Oh, admin/admin, close it now.

**Comment by A-Dechorgnat** [comment]
Notice that you can modify the password or create a new administrator before removing the default one
