### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by UAnton** [inkscope/inkscope#78]
Hi! Please write normal manual for install. You manula is wrong and not working! All confused and wonder what and where should be set!

**Comment by A-Dechorgnat** [comment]
Hi,

The (rather) up to date installation process is described [there](http://inkscope.blogspot.fr/2015/12/inkscope-v13-installation-on-debian.html) and completed [there](https://github.com/inkscope/inkscope/wiki/Monitoring-in-Inkscope-with-collectd-and-influxDB)

I know we need a better doc 

Alain

**Comment by UAnton** [comment]
I try, but I don't understand how it works, because installation manula differs from picture in start of manual. How I can guess where I can install rest-api? In manual I don't see this information! (((

**Comment by A-Dechorgnat** [comment]
The picture in start of "manual" is rather a functional view.

For Inkscope, you need a server where you install all Inkscope packages. This server can be a Ceph node, but It is better if it is independent.
For ceph-rest-api configuration, it's described [here](http://inkscope.blogspot.fr/2015/03/inkscope-and-ceph-rest-api.html); the best solution is "ceph-rest-api as a WSGI application" in the second part of the article.

**Comment by UAnton** [comment]
Thanks for answer! I try!

**Comment by UAnton** [comment]
Not work for me. Try Ubuntu, CentOS...
[](http://prntscr.com/bgoin7)

**Comment by UAnton** [comment]
I have never seen in my life such a horrible program!

**Comment by A-Dechorgnat** [comment]
I don't understand how you manage to have it not working!
Follow the doc step by step, and don't be so insulting!
It's open source! and free!
