### ISSUE TITLE
Incomplete dashboard for ceph cluster without MDS.

### ISSUE THREAD

**Issue by randrewz** [inkscope/inkscope#79]
If a ceph cluster contains no MDS, status.json returns no "mdsmap" in JSON at all.
In this situation statusApp.js crashes on line 167 with error:

`TypeError: Cannot read property 'up:standby' of undefined`

This leads to complete rendering of inkscope v1.4.0 dashboard.
![screenshot from 2016-06-15 20 19 51](https://cloud.githubusercontent.com/assets/19957070/16090106/d38b75e8-3336-11e6-91c9-bd3dbf6a405b.png)

Something like the following patch may help:
```
--- statusApp.js.bak    2016-05-23 12:21:44.000000000 +0300
+++ statusApp.js        2016-06-15 20:11:14.000000000 +0300
@@ -163,8 +163,10 @@
                 if ( typeof  data.output.pgmap.degraded_objects === "undefined" ) $scope.pgmap.degraded_objects=0;
 
 
-                $scope.mdsmap = data.output.mdsmap;
-                $scope.mdsmap.up_standby = data.output.mdsmap["up:standby"];
+                if ( typeof data.output.mdsmap  != "undefined" ) {
+                    $scope.mdsmap = data.output.mdsmap;
+                    $scope.mdsmap.up_standby = data.output.mdsmap["up:standby"];
+                }
                 $scope.percentUsed = $scope.pgmap.bytes_used / $scope.pgmap.bytes_total;

```

**Comment by A-Dechorgnat** [comment]
Can you verify if cba0a7e helps?

**Comment by randrewz** [comment]
Yes, it helped. Thank you.
