### ISSUE TITLE
cephprobe only works if OSD's mounted in default location

### ISSUE THREAD

**Issue by btucker-mintel** [inkscope/inkscope#80]
Ceph OSD's can be setup with the data at any location (specified on creation), however cephprobe.py is hard-coded to use '/var/lib/ceph/osd/'+clusterName+'-'+str(osd["osd"]

https://github.com/inkscope/inkscope/blob/master/inkscopeProbe/cephprobe.py:398

**Comment by A-Dechorgnat** [comment]
Using a custom path for the OSD data location can be very confusing. What kind of path did you use?

**Comment by JrCs** [comment]
Just one question. In the wiki it is said:
> cephprobe ... must be installed on only one machine running a Ceph node
But a ceph node can be only a monitor so why the cephprobe.py script is trying to look at one OSD ?

**Comment by btucker-mintel** [comment]
cephprobe connects the "ceph" information with the "system" information
stored in the mongodb by the sysprobe's

Usinga custom path is quite straightforward when using ceph-deploy....you
just specify it when you create the osd and it creates the appropriate
symlink to it in /var/ceph/osd/

The path we were planning to use was /data/osd

The problem is that cephprobe is looking for a mountpoint in /var/ceph/osd,
rather than the existence of a path

On 23 June 2016 at 15:26, Yves Blusseau <notifications@github.com> wrote:

> Just one question. In the wiki it is said:
>
> cephprobe ... must be installed on only one machine running a Ceph node
> But a ceph node can be only a monitor so why the cephprobe.py script is
> trying to look at one OSD ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/inkscope/inkscope/issues/80#issuecomment-228066789>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATHP6V-j3waktRyJOwohT-S_fFppH7_zks5qOpd4gaJpZM4I5iow>
> .
>

-- 

Mintel Group Ltd | 11 Pilgrim Street | London | EC4V 6RN
Registered in England: Number 1475918. | VAT Number: GB 232 9342 72

Contact details for our other offices can be found at 
http://www.mintel.com/office-locations.

This email and any attachments may include content that is confidential, 
privileged 
or otherwise protected under applicable law. Unauthorised disclosure, 
copying, distribution 
or use of the contents is prohibited and may be unlawful. If you have 
received this email in error,
including without appropriate authorisation, then please reply to the 
sender about the error 
and delete this email and any attachments.
