### ISSUE TITLE
no monitoring data

### ISSUE THREAD

**Issue by chengweiv5** [inkscope/inkscope#86]
Hi there, 

I setup a influxdb in localhost, and ensure that ip:8086 listen by influxdb and have a correct inkscope.conf because I didn't see any error from chrome developer tools console.

![console](https://cloud.githubusercontent.com/assets/689798/18335647/8c3d7e60-75b3-11e6-9d35-a0e31726a138.png)

However, inkscope doesn't show anything in monitoring page.

I ran below commands from console

```
# curl -G http://ip:8086/query?pretty=true  --data-urlencode "q=SELECT mean(\"value\")FROM \"ceph-ceph_value\" WHERE \"instance\" = 'cluster' AND time > now() - 2h GROUP BY time(3m), \"type_instance\" fill(none)" --data-urlencode "db=collectd"
{
    "results": [
        {
            "error": "database not found: collectd"
        }
    ]
}
```

So where is the database collectd?

I also grep the source code and I didn't found any **document** nor **code** who will create that database and write the monitoring data.

So how can I get monitoring data works?

**Comment by chengweiv5** [comment]
OK, I think I found a page https://github.com/inkscope/inkscope/wiki/Monitoring-in-Inkscope-with-collectd-and-influxDB , I'll give a try

**Comment by chengweiv5** [comment]
I successfully get monitoring data, cluster, osds, pools works find except cluster latency, the console complaints like below

![inkscope-10](https://cloud.githubusercontent.com/assets/689798/18337450/4d343f0a-75c3-11e6-951b-4ab410e05bd6.png)

I checked the code, yes, it defined scale with a undefined because series doesn't has scale key as I get data from command like

```
curl -G http://ip:8086/query?pretty=true  --data-urlencode "q=SELECT mean(\"value\") FROM \"ceph-ceph_value\" WHERE \"instance\" = 'cluster' AND time > now() - 2h GROUP BY time(3m), \"type_instance\" fill(none)" --data-urlencode "db=collectd" | jq .
```

**Comment by laggeduout** [comment]
I have the same managed to find the below in collectd syslog:

Sep  9 10:24:05 ceph-mon1 collectd[40509]: ceph: failed to get stats :: list index out of range :: Traceback (most recent call last):#012  File "/usr/lib/collectd/plugins/ceph/base.py", line 114, in read_callback#012    stats = self.get_stats()#012  File "/usr/lib/collectd/plugins/ceph/ceph_latency_plugin.py", line 67, in get_stats#012    data[ceph_cluster]['cluster']['stddev_latency'] = results[1]#012IndexError: list index out of range
Sep  9 10:24:05 ceph-mon1 collectd[40509]: Unhandled python exception in read callback: UnboundLocalError: local variable 'stats' referenced before assignment
Sep  9 10:24:05 ceph-mon1 collectd[40509]: read-function of plugin `python.ceph_latency_plugin' failed. Will suspend it for 120.000 seconds.

**Comment by laggeduout** [comment]
Looking at the code I think it needed a pool created called 'data' I created this and the graphs started working

**Comment by chengweiv5** [comment]
@laggeduout Thanks, I didn't take a look at collectd ceph plugin yet, I'll try your suggestion, thanks.

**Comment by chengweiv5** [comment]
@laggeduout you're right, ceph_latency_plugin invoke `rados bench` command to get latency which target to `data` pool.
