### ISSUE TITLE
osdMap

### ISSUE THREAD

**Issue by laggeduout** [inkscope/inkscope#88]
Is it normal for the osd map to show grey in this way even though the osd's report 'up'

![Uploading map.PNG…]()

**Comment by laggeduout** [comment]
![map](https://cloud.githubusercontent.com/assets/6632585/18385423/762f498e-7688-11e6-8da9-0c659564ea7e.PNG)

**Comment by A-Dechorgnat** [comment]
Same as closed #46: not reproduced
May be there are interesting things in the javascript console?

**Comment by laggeduout** [comment]
![js](https://cloud.githubusercontent.com/assets/6632585/18678476/10b898ba-7f54-11e6-99a3-51c2c057032d.PNG)

I think it is because my osd id's are not sequential - see osd output below:

osd.22: osd_max_backfills = '1'
osd.23: osd_max_backfills = '1'
osd.28: osd_max_backfills = '1'

If you look at the image it seems any osd after osd.23 (the gap) does not show green.

**Comment by A-Dechorgnat** [comment]
It's probably a confusion between an array index and the osd id.
I'll try to reproduce.
