### ISSUE TITLE
monitoring doesn't show X-axes correctly

### ISSUE THREAD

**Issue by chengweiv5** [inkscope/inkscope#89]
If I try to show a period of graphing exceeds the window has monitoring data, then some graphs doesn't show X-axes correctly, which doesn't draw the graph without data, see below screenshot, only PG graph expands correctly.

![inkscope](https://cloud.githubusercontent.com/assets/689798/18612059/6238d9a4-7d81-11e6-80be-53d1dc04b719.png)

**Comment by A-Dechorgnat** [comment]
Well, I'm not sure showing a period where there are no data is very usefull, so I would have said that it is rather PG graph which is not correct.
By the way, this is not consistent between this page graphs.

**Comment by chengweiv5** [comment]
yes, agreed.

**Comment by jthiyagu** [comment]
Hi chengweiv5,

Can you please share the procedure that you followed to install and configure influxdb and collectd to capture performance stats. ?

**Comment by A-Dechorgnat** [comment]
This is described here:
https://github.com/inkscope/inkscope/wiki/Monitoring-in-Inkscope-with-collectd-and-influxDB
