### ISSUE TITLE
pools/pgs/osds doesn't show osd that is in out status

### ISSUE THREAD

**Issue by shuiyouhan** [inkscope/inkscope#92]
If I chack an  osd  that is in out status,the page will display  garbled. like this, osd.2 is out
![qq 20161017150240](https://cloud.githubusercontent.com/assets/22878488/19428278/c71473ea-947b-11e6-8aa9-18035f17338f.png)

**Comment by Dechorgnat** [comment]
If the OSD is out, they are no pg to display.

2016-10-17 9:10 GMT+02:00 shuiyouhan <notifications@github.com>:

**Comment by shuiyouhan** [comment]
got it, I think it's better to dispaly no pg rather than disorder codes .
![Uploading QQ截图20161021093523.png…]()
