### ISSUE TITLE
Jewel :ServerSelectionTimeoutError: No servers found yet, referer

### ISSUE THREAD

**Issue by Floink99** [inkscope/inkscope#93]
Hi, 
i installed inkscope 1.4 For jewel on ubuntu 16.04 and have some issues. 

I have some infos on index page (like number of pgs or pools ; but nothing else) 

The mongodb is filled by cephprobe and sysprobe. 
i'm having [wsgi_error] in /var/log/inkscope/webserver_error.log (i formatted the output) : 

_Target WSGI script '/var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi' cannot be loaded as Python module
mod_wsgi (pid=24737): Exception occurred processing WSGI script '/var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi'.
"/var/www/inkscope/inkscopeCtrl/inkscopeCtrlcore.py"
 if db.inkscope_users.count() == 0:
 return self._count(cmd, collation),
File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py" , line 859, in _socket_for_reads
with self._get_socket(read_preference) as sock_info:,
File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__,
 return self.gen.next(),
 File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 823, in _get_socket,
server = self._get_topology().select_server(selector)
File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 214, in select_server,
address)),
File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 189, in select_servers,
self._error_message(selector)),
ServerSelectionTimeoutError: No servers found yet, referer http://XX.XX.XX.XX:8080/inkscopeViz/index.html_

I guess there is an issue with mongo but i don't see why. I'm logged as nothing in the navigator
I've got this in database : 
> use  3807f215-75ab-48xxxxxxxxxxxxxxxxxxx
switched to db 3807f215-75ab-48xxxxxxxxxxxxxxxx
> db.inkscope_users.count()
0
No users created automatically as suggested in the script (i tried manually) 
i already dropped database and started again with fresh DB

Curl command is responding after a few second and is very slow : 
ex: curl  http://localhost:8080/ceph-rest-api/df.json ok 
Files like /opt/inkscope/etc/inkscope.conf  : 
{
    "ceph_conf": "/etc/ceph/ceph.conf",
    "ceph_rest_api": "SERVERA:8080",
    "ceph_rest_api_subfolder": "ceph_rest_api",
    "mongodb_host" : "SERVERB",
    "mongodb_set" : "mongodb0:27017,mongodb1:27017,mongodb2:27017",
    "mongodb_replicaSet" : "replmongo0",
    "mongodb_read_preference" : "ReadPreference.SECONDARY_PREFERRED",
    "mongodb_port" : 27017,
    "mongodb_user":"inkscope",
    "mongodb_passwd":"test",
    "is_mongo_authenticate" : 0,
    "is_mongo_replicat" : 0,
    "influxdb_endpoint":"",
    "cluster": "ceph",
    "platform": "Jewel",
    "status_refresh": 3,
    "osd_dump_refresh": 3,
    "pg_dump_refresh": 60,
    "crushmap_refresh": 60,
    "df_refresh": 60,
    "cluster_window": 1200,
    "osd_window": 1200,
    "pool_window": 1200,
    "mem_refresh": 60,
    "swap_refresh": 600,
    "disk_refresh": 60,
    "partition_refresh": 60,
    "cpu_refresh": 30,
    "net_refresh": 30,
    "mem_window": 1200,
    "swap_window": 3600,
    "disk_window": 1200,
    "partition_window": 1200,
    "cpu_window": 1200,
    "net_window": 1200,
    "inkscope_root" : "inkscope_host:inkscope_port",
    "radosgw_url": "http://SERVERA:7480",
    "radosgw_admin": "admin",
    "radosgw_key": "access-key",
    "radosgw_secret": "secret-key"
}

and /etc/apache2/sites-enabled/inkScope.conf on SERVERA 
cat /etc/apache2/sites-enabled/inkScope.conf
<VirtualHost *:8080>
    ServerName  localhost
    ServerAdmin webmaster@localhost

    DocumentRoot /var/www/inkscope
    <Directory "/var/www/inkscope">
        Options All
        AllowOverride All
    </Directory>

    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Directory "/usr/lib/cgi-bin">
        AllowOverride None
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
        Order allow,deny
        Allow from all
    </Directory>

    WSGIScriptAlias /inkscopeCtrl /var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi
    <Directory "/var/www/inkscope/inkscopeCtrl">
        Order allow,deny
        Allow from all
    </Directory>

    WSGIScriptAlias /ceph_rest_api /var/www/inkscope/inkscopeCtrl/ceph-rest-api.wsgi
    <Directory "/var/www/inkscope/inkscopeCtrl">
         Require all granted
    </Directory>

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    ProxyRequests Off  # we want  a "Reverse proxy"

    # For a ceph_rest_api in wsgi mode
    ProxyPass /ceph-rest-api/ http://localhost:8080/ceph_rest_api/api/v0.1/

    # For a standalone ceph_rest_api, uncomment the next line and comment the previous one
 #    ProxyPass /ceph-rest-api/ http://localhost:5000/api/v0.1/

    ErrorLog /var/log/inkscope/webserver_error.log
    CustomLog /var/log/inkscope/webserver_access.log common

</VirtualHost>

Thanks in advance for your Help, any tips or procedure would be great.

**Comment by goodard** [comment]
Hi,

Do you have admin user created?

for example:

radosgw-admin user create --uid=inkscope --display-name="Inkscope admin"
--access-key=accesskey --secret=secretkey    --system

Also in your inkscope.conf you have to change

"inkscope_root" : "inkscope_host:inkscope_port"
to
"inkscope_root" : "SERVERA:8080"

Copy /opt/inkscope/etc/inkscope.conf to hosts where you have cephprobe and
sysprobe installed.


Here is our working apache config:

<VirtualHost *:8080>
    ServerName  localhost
    ServerAdmin webmaster@localhost

    DocumentRoot /var/www/inkscope
    <Directory "/var/www/inkscope">
        Options All
        AllowOverride All
    </Directory>

    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Directory "/usr/lib/cgi-bin">
        AllowOverride None
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
        Order allow,deny
        Allow from all
    </Directory>

    WSGIScriptAlias /inkscopeCtrl
/var/www/inkscope/inkscopeCtrl/inkscopeCtrl.wsgi
    <Directory "/var/www/inkscope/inkScopeCtrl">
        Order allow,deny
        Allow from all
    </Directory>

    <Directory "/var/www/inkscope/inkScopeCtrl">
         Require all granted
    </Directory>

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn
    RewriteEngine On
    RewriteRule ^/ceph-rest-api/(.*)$ /ceph_rest_api/api/v0.1/$1
[R=301,NC,L]
    WSGIScriptAlias /ceph_rest_api
/var/www/inkscope/inkscopeCtrl/ceph-rest-api.wsgi
    <Directory "/var/www/inkscope/inkScopeCtrl">
        Require all granted
    </Directory>

    ErrorLog /var/log/inkscope/webserver_error.log
    CustomLog /var/log/inkscope/webserver_access.log common

</VirtualHost>



regards
Marko

**Comment by Floink99** [comment]
Hi, 
thanks Marko ; 

Things are going better now. 
I fought a bit with flask-login witch is coming in version 0.4 and some  attributes seems to be deprecated, i put 0.3.2 and thongs are going well. 

Now i'm logged in admin but I can't see everything on main page. I have some information but status is unavailable as monitor status and pies on pgs or OSDs either.
I have this error in cephprobe.log : 
Traceback (most recent call last):
  File "/opt/inkscope/bin/cephprobe.py", line 656, in run
    self.function(*self.args)
  File "/opt/inkscope/bin/cephprobe.py", line 277, in process_status
    monneti = db.net.find_one({"$where": "this.inet.addr === '"+hostaddr+"'"})
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 604, in find_one
    for result in self.find(spec_or_id, *args, **kwargs).limit(-1):
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 904, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 848, in _refresh
    self.__uuid_subtype))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 800, in __send_message
    self.__uuid_subtype)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 100, in _unpack_response
    error_object["$err"])
OperationFailure: database error: TypeError: Cannot read property 'addr' of null near ''MON-A"

I saw an issue [#43](https://github.com/inkscope/inkscope/issues/43) on this and modified the monetti var without success. 
I notice that this mon is a Virtual machine. 
I don't see any others errors in apache, web_server or sysprobe either. 

I hope there's no more python dependencies or version issues with ubuntu 16.04. I also downgrade Pymongo version from 3.10 to 2.6.3 according to [#87](https://github.com/inkscope/inkscope/issues/87)

a pip list would be great to know the proper versions. 

Thanks for your Help.  :) 

ps : (Thanks for your apache conf... better than proxypass)  :')

**Comment by Floink99** [comment]
I think we can close this issue, 
These errors i mentionned in title are now resolved. 

I still have issues : I swiched my case on  #87

Thanks for this anyway. 
brgrds
