### ISSUE TITLE
How to remove a decomissioned OSD from the inkscope ui ?

### ISSUE THREAD

**Issue by primeroz** [inkscope/inkscope#94]
I had to replace an OSD in my cluster but is still showing up , marked as red , in inkscope ui

Looked in the mongodb and i can see it referenced in many different collections so i think there must be a clean way to remove a node ? 

The node has actually died and sysprobe has not been running there for at least 3 days now

**Comment by A-Dechorgnat** [comment]
It seems to be solved in issue #72 .
The fix is in release 1.4.0.2 (19 May 2016)

Could you verify and confirm, please?

Best regards

**Comment by primeroz** [comment]
I see, i ll have a look at it.

I do run a very old version and might be a while before i get to update so you might want to close this instead of waiting for me.

Thanks!

**Comment by A-Dechorgnat** [comment]
Don't worry, I can wait.
